# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_interestovertime_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestovertime',
            name='geo_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
